changelog:
  categories:             # リリースノートのカテゴリ設定
    - title: Enhancement  # リリースノートへ「Enhancement」というカテゴリを作成する
      labels:
        - enhancement     # 「Enhancement」へ掲載するプルリクエストのラベルを指定する
    - title: Bug Fixes
      labels:             # プルリクエストのラベルは複数定義できる
        - bug
        - fixes
  exclude:                # リリースノートの除外設定
    labels:               # 除外するラベル
      - dependencies
    authors:              # 除外するプルリクエスト作成者
      - dependabot
