name: Add mask
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      PASSWORD: hoge123HOGE
    steps:
      - run: echo "::add-mask::${PASSWORD}" # ログ出力時にマスク
      - run: echo "${PASSWORD}"
