name: Conditions
run-name: Run Conditions by ${{ github.actor }}
on: push
jobs:
  skip-or-run:
    if: ${{ github.actor == 'octocat' }}  # octocatアカウント以外は実行をスキップ
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
  fail:
    if: false                 # NOTE: failしないように実行をスキップ
    runs-on: ubuntu-latest
    steps:
      - run: exit 1           # 終了ステータスがゼロ以外なので、エラーが発生する
      - run: echo "World"
        if: ${{ failure() }}  # エラーが発生しても、failure関数があるので実行される
