name: Job summaries
run-name: Job summaries
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      # NOTE: actionlint error対応
      # > Consider using { cmd1; cmd2; } >> file instead of individual redirects
      # https://www.shellcheck.net/wiki/SC2129
      - run: |
          {
            echo "## Example Title :rocket:"
            echo "- first line"
            echo "- second line"
            echo "\`\`\`typescript"
            echo "const hoge = () => console.log('hoge.');"
            echo "\`\`\`"
          } >> "${GITHUB_STEP_SUMMARY}"
