name: Call Reusable Workflows
run-name: Call Reusable Workflows
on: pull_request
jobs:
  call:
    # Reusable Workflowsの指定
    # NOTE: stepsではなく、jobsで指定する
    uses: ./.github/workflows/reusable-workflows.yml
    with:
      pr-number: ${{ github.event.pull_request.number }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
  print:
    needs: [call]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Result> ${MESSAGE}"
        env:
          MESSAGE: ${{ needs.call.outputs.message }}
