name: Reusable Workflows
run-name: Reusable Workflows
on:
  workflow_call:  # Reusable Workflowsを起動するイベント
    inputs:
      pr-number:
        type: string
        default: ${{ github.event.pull_request.number }}
        required: false
        description: プルリクエスト番号
    secrets:
      token:
        required: true
        description: GitHubトークン
    outputs:
      message:
        value: ${{ jobs.comment.outputs.pr-comment }}
        description: 投稿メッセージ
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      PR_NUMBER: ${{ inputs.pr-number }}
      PR_COMMENT: "Welcome, ${{ github.actor }}"
      GITHUB_TOKEN: ${{ secrets.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Get PR comments & Check a comment already submitted
        id: get-and-check-pr-comments
        run: |
          # PRのコメント一覧を取得
          comments=$(gh pr view --json comments "${PR_NUMBER}" | jq '.comments[] | .body')
          # メッセージがすでに投稿済か確認
          # NOTE: actionlint error対応
          # https://www.shellcheck.net/wiki/SC2199
          has_a_comment=false
          for comment in "${comments[@]}"
          do
            if [ "$comment" == "${PR_COMMENT}" ]; then
              has_a_comment=true
              break
            fi
          done
          echo "has_a_comment=${has_a_comment}" >> "${GITHUB_OUTPUT}"
      - name: Submit a PR comment
        id: submit-pr-comment
        run: |
          gh pr comment "${PR_NUMBER}" --body "${PR_COMMENT}"
          echo "body=${body}" >> "${GITHUB_OUTPUT}"
        if: ${{ !(fromJson(steps.get-and-check-pr-comments.outputs.has_a_comment)) }}
    outputs:
      pr-comment: ${{ steps.submit-pr-comment.outputs.body }}
