name: Reusable Workflows
run-name: Reusable Workflows
permissions: {}
on:
  workflow_call:  # Reusable Workflowsを起動するイベント
    inputs:
      pr-number:
        type: string
        default: ${{ github.event.pull_request.number }}
        required: false
        description: プルリクエスト番号
    secrets:
      token:
        required: true
        description: GitHubトークン
    outputs:
      message:
        value: ${{ jobs.comment.outputs.pr-comment }}
        description: 投稿メッセージ
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      PR_NUMBER: ${{ inputs.pr-number }}
      PR_COMMENT: "Welcome, ${{ github.actor }}"
      GITHUB_TOKEN: ${{ secrets.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Check a comment already submitted
        id: check-pr-comments
        run: |
          # PRのコメント一覧に、同一投稿メッセージが存在するかチェック
          has_a_comment="$(
            gh pr view --json comments "${PR_NUMBER}" \
            | jq '[.comments[].body] | any(. == "'"${PR_COMMENT}"'")'
          )"
          echo "has_a_comment=${has_a_comment}" >> "${GITHUB_OUTPUT}"
      - name: Submit a PR comment
        id: submit-pr-comment
        run: |
          gh pr comment "${PR_NUMBER}" --body "${PR_COMMENT}"
          echo "body=${body}" >> "${GITHUB_OUTPUT}"
        if: ${{ !(fromJson(steps.check-pr-comments.outputs.has_a_comment)) }}
    outputs:
      pr-comment: ${{ steps.submit-pr-comment.outputs.body }}
