name: Secret Scan with Secretlint
run-name: Secret Scan with Secretlint
permissions:
  contents: read
on: pull_request
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |  # --maskSecrets フラグでログ出力をマスク
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" \
            secretlint/secretlint secretlint --maskSecrets '**/*'
