name: Sequential jobs
run-name: Sequential jobs
on: push
jobs:
  first:                                    # 依存ジョブがないため最初に実行される（並列）
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job"
  second:                                   # 依存ジョブがないため最初に実行される（並列）
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Second job"
  third:                                    # secondジョブの後に実行される（逐次）
    runs-on: ubuntu-latest
    needs: [second]                         # NOTE: needsキーへ依存するジョブIDを指定すると、逐次実行となる
    steps:
      - run: echo "Third job"
  forth:                                    # thirdジョブの後に実行される（逐次）
    runs-on: ubuntu-latest
    needs: [third]
    steps:
      - run: echo "Forth job"
  fifth:                                    # firstジョブとsecondジョブが両方とも完了後に実行される（逐次）
    runs-on: ubuntu-latest
    needs: [first, second]
    steps:
      - run: sleep 10 && echo "Fifth job"
