name: Share job data
run-name: Share job data
on: push
jobs:
  before:
    runs-on: ubuntu-latest
    steps:
      - id: generate
        run: echo "result=Before" >> "${GITHUB_OUTPUT}" # ステップレベルの出力値
    outputs:
      result: ${{ steps.generate.outputs.result }}      # ジョブレベルの出力値
  after:
    runs-on: ubuntu-latest
    needs: [before]
    steps:
      - env:
          RESULT: ${{ needs.before.outputs.result }}    # 依存ジョブの出力値を参照
        run: echo "Shared data from ${RESULT}"
