name: Share data
on: push
jobs:
  github-output:
    name: Sharing by GITHUB_OUTPUT
    runs-on: ubuntu-latest
    steps:
      - id: src # ステップIDを設定
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - env:
          RESULT_1: ${{ steps.src.outputs.result }}
        run: echo "${RESULT_1}"
  github-env:
    name: Sharing by GITHUB_ENV
    runs-on: ubuntu-latest
    steps:
      - run: echo "RESULT_2=World" >> "${GITHUB_ENV}"
      - run: echo "${RESULT_2}"