name: Static analysis
run-name: actionlint
on:
  pull_request:
    paths: ['.github/workflows/*.ya?ml']
defaults:                                           # デフォルトシェル
  run:
    shell: bash
concurrency:                                        # ワークフロー多重起動時の自動キャンセル
  group: ${{ github.workflow }}-${{ github.ref }}   # NOTE: 同一グループの場合、コミット追加時に、古いワークフローの実行を自動キャンセル
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5                              # タイムアウト
    steps:
      - uses: actions/checkout@v4
      - run: |                                      # 静的解析の実行
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest
